/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.bhuyanp.order.client.api;

import io.github.bhuyanp.order.client.model.CreateOrderRequest;
import io.github.bhuyanp.order.client.model.Order;
import io.github.bhuyanp.order.client.model.ProblemDetail;
import java.util.UUID;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-13T18:42:15.029064-05:00[America/New_York]", comments = "Generator version: 7.16.0")
public interface OrderServiceApi {

    /**
     * POST /api/order : Create Order
     * Creates an order and returns order id.
     *
     * @param createOrderRequest  (required)
     * @return Invalid request. (status code 400)
     *         or Unable to create order. (status code 500)
     *         or Created (status code 201)
     */
    @HttpExchange(
        method = "POST",
        value = "/api/order",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Order> createOrder(
         @RequestBody CreateOrderRequest createOrderRequest
    );


    /**
     * GET /api/order/{orderId} : Get Order By Id
     * Update an order.
     *
     * @param orderId  (required)
     * @return Order not found. (status code 404)
     *         or Invalid request. (status code 400)
     *         or Unable to fetch order. (status code 500)
     *         or OK (status code 200)
     */
    @HttpExchange(
        method = "GET",
        value = "/api/order/{orderId}",
        accept = { "application/json" }
    )
    ResponseEntity<Order> getOrder(
         @PathVariable("orderId") UUID orderId
    );


    /**
     * PUT /api/order : Update Order
     * Update an order.
     *
     * @param order  (required)
     * @return Order not found. (status code 404)
     *         or Invalid request. (status code 400)
     *         or Unable to update order. (status code 500)
     *         or No Content (status code 204)
     */
    @HttpExchange(
        method = "PUT",
        value = "/api/order",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> updateOrder(
         @RequestBody Order order
    );

}
