/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.bhuyanp.inventory.client.api;

import io.github.bhuyanp.inventory.client.model.InventoryRequest;
import io.github.bhuyanp.inventory.client.model.InventoryResponse;
import io.github.bhuyanp.inventory.client.model.ProblemDetail;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-15T08:20:28.530530-05:00[America/New_York]", comments = "Generator version: 7.16.0")
public interface InventoryServiceApi {

    /**
     * POST /api/inventory : Block inventory
     * Block the inventory for a given order.
     *
     * @param inventoryRequest  (required)
     * @return Invalid request. (status code 400)
     *         or Unable to block the inventory. (status code 500)
     *         or Created (status code 201)
     */
    @HttpExchange(
        method = "POST",
        value = "/api/inventory",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<InventoryResponse> blockInventory(
         @RequestBody InventoryRequest inventoryRequest
    );


    /**
     * DELETE /api/inventory/{orderId} : Release inventory hold
     * Releases the blocked inventory back into the pool.
     *
     * @param orderId  (required)
     * @return Order id missing. (status code 404)
     *         or Unable to release the inventory. (status code 500)
     *         or No Content (status code 204)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/api/inventory/{orderId}",
        accept = { "*/*" }
    )
    ResponseEntity<Void> releaseInventory(
         @PathVariable("orderId") String orderId
    );

}
