/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.bhuyanp.shipping.client.api;

import io.github.bhuyanp.shipping.client.model.ProblemDetail;
import io.github.bhuyanp.shipping.client.model.ShippingRequest;
import io.github.bhuyanp.shipping.client.model.ShippingResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-06T06:09:50.875063-05:00[America/New_York]", comments = "Generator version: 7.16.0")
public interface ShippingServiceApi {

    /**
     * POST /api/shipping : Ship order
     * Ship the products in the purchase order and return the tracking id.
     *
     * @param shippingRequest  (required)
     * @return Invalid request. (status code 400)
     *         or Unable to ship order. (status code 500)
     *         or Created (status code 201)
     */
    @HttpExchange(
        method = "POST",
        value = "/api/shipping",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<ShippingResponse> shipOrder(
         @RequestBody ShippingRequest shippingRequest
    );

}
