/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.bhuyanp.notification.client.api;

import io.github.bhuyanp.notification.client.model.OrderCompletionNotification;
import io.github.bhuyanp.notification.client.model.OrderConfirmationNotification;
import io.github.bhuyanp.notification.client.model.OrderFailureNotification;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-07T06:29:40.230014-05:00[America/New_York]", comments = "Generator version: 7.16.0")
public interface OrderNotificationApi {

    /**
     * POST /api/notification/order/completion
     *
     * @param orderCompletionNotification  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/api/notification/order/completion",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> sendOrderCompletionNotification(
         @RequestBody OrderCompletionNotification orderCompletionNotification
    );


    /**
     * POST /api/notification/order/confirmation
     *
     * @param orderConfirmationNotification  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/api/notification/order/confirmation",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> sendOrderConfirmationNotification(
         @RequestBody OrderConfirmationNotification orderConfirmationNotification
    );


    /**
     * POST /api/notification/order/failure
     *
     * @param orderFailureNotification  (required)
     * @return OK (status code 200)
     */
    @HttpExchange(
        method = "POST",
        value = "/api/notification/order/failure",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<Void> sendOrderFailureNotification(
         @RequestBody OrderFailureNotification orderFailureNotification
    );

}
