/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.16.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package io.github.bhuyanp.payment.client.api;

import io.github.bhuyanp.payment.client.model.PaymentRequest;
import io.github.bhuyanp.payment.client.model.ProblemDetail;
import io.github.bhuyanp.payment.client.model.ProcessPaymentResponse;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.service.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-11-10T11:22:49.127572-05:00[America/New_York]", comments = "Generator version: 7.16.0")
public interface PaymentServiceApi {

    /**
     * POST /api/payment : Process payment
     * Processed payment for an order and return a payment confirmation id.
     *
     * @param paymentRequest  (required)
     * @return Invalid request. (status code 400)
     *         or Unable to process payment. (status code 500)
     *         or Created (status code 201)
     */
    @HttpExchange(
        method = "POST",
        value = "/api/payment",
        accept = { "application/json" },
        contentType = "application/json"
    )
    ResponseEntity<ProcessPaymentResponse> processPayment(
         @RequestBody PaymentRequest paymentRequest
    );


    /**
     * DELETE /api/payment : Refund payment
     * Refunds payment back based on the payment ref id.
     *
     * @param paymentRequest  (required)
     * @return Payment ref id missing. (status code 404)
     *         or Unable to refund the payment. (status code 500)
     *         or No Content (status code 204)
     */
    @HttpExchange(
        method = "DELETE",
        value = "/api/payment",
        accept = { "*/*" },
        contentType = "application/json"
    )
    ResponseEntity<Void> refundPayment(
         @RequestBody PaymentRequest paymentRequest
    );

}
